# Generated by Django 2.1.5 on 2019-01-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190123_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('recorded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
