# Generated by Django 2.1.5 on 2019-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pressure'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='humidity',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='humidity',
            name='recorded_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
